export interface Nationality {
  value: string;
  viewValue: string;
}

export const NATIONALITIES: Nationality[] = [
   { value: 'ALB', viewValue: 'Albania' },
   { value: 'DZA', viewValue: 'Algeria' },
   { value: 'AND', viewValue: 'Andorra' },
   { value: 'AGO', viewValue: 'Angola' },
   { value: 'ATG', viewValue: 'Antigua and Barbuda' },
   { value: 'ARG', viewValue: 'Argentina' },
   { value: 'ARM', viewValue: 'Armenia' },
   { value: 'AUS', viewValue: 'Australia' },
   { value: 'AUT', viewValue: 'Austria' },
   { value: 'AZE', viewValue: 'Azerbaijan' },
   { value: 'BHS', viewValue: 'Bahamas' },
   { value: 'BHR', viewValue: 'Bahrain' },
   { value: 'BGD', viewValue: 'Bangladesh' },
   { value: 'BRB', viewValue: 'Barbados' },
   { value: 'BLR', viewValue: 'Belarus' },
   { value: 'BEL', viewValue: 'Belgium' },
   { value: 'BLZ', viewValue: 'Belize' },
   { value: 'BEN', viewValue: 'Benin' },
   { value: 'BTN', viewValue: 'Bhutan' },
   { value: 'BOL', viewValue: 'Bolivia' },
   { value: 'BIH', viewValue: 'Bosnia and Herzegovina' },
   { value: 'BWA', viewValue: 'Botswana' },
   { value: 'BRA', viewValue: 'Brazil' },
   { value: 'BRN', viewValue: 'Brunei' },
   { value: 'BGR', viewValue: 'Bulgaria' },
   { value: 'BFA', viewValue: 'Burkina Faso' },
   { value: 'BDI', viewValue: 'Burundi' },
   { value: 'CPV', viewValue: 'Cabo Verde' },
   { value: 'KHM', viewValue: 'Cambodia' },
   { value: 'CMR', viewValue: 'Cameroon' },
   { value: 'CAN', viewValue: 'Canada' },
   { value: 'CAF', viewValue: 'Central African Republic' },
   { value: 'TCD', viewValue: 'Chad' },
   { value: 'CHL', viewValue: 'Chile' },
   { value: 'CHN', viewValue: 'China' },
   { value: 'COL', viewValue: 'Colombia' },
   { value: 'COM', viewValue: 'Comoros' },
   { value: 'COD', viewValue: 'Congo (Democratic Republic of the)' },
   { value: 'COG', viewValue: 'Congo' },
   { value: 'CRI', viewValue: 'Costa Rica' },
   { value: 'CIV', viewValue: "Côte d'Ivoire" },
   { value: 'HRV', viewValue: 'Croatia' },
   { value: 'CUB', viewValue: 'Cuba' },
   { value: 'CYP', viewValue: 'Cyprus' },
   { value: 'CZE', viewValue: 'Czechia' },
   { value: 'DNK', viewValue: 'Denmark' },
   { value: 'DJI', viewValue: 'Djibouti' },
   { value: 'DMA', viewValue: 'Dominica' },
   { value: 'DOM', viewValue: 'Dominican Republic' },
   { value: 'ECU', viewValue: 'Ecuador' },
   { value: 'EGY', viewValue: 'Egypt' },
   { value: 'SLV', viewValue: 'El Salvador' },
   { value: 'GNQ', viewValue: 'Equatorial Guinea' },
   { value: 'ERI', viewValue: 'Eritrea' },
   { value: 'EST', viewValue: 'Estonia' },
   { value: 'SWZ', viewValue: 'Eswatini' },
   { value: 'ETH', viewValue: 'Ethiopia' },
   { value: 'FJI', viewValue: 'Fiji' },
   { value: 'FIN', viewValue: 'Finland' },
   { value: 'FRA', viewValue: 'France' },
   { value: 'GAB', viewValue: 'Gabon' },
   { value: 'GMB', viewValue: 'Gambia' },
   { value: 'GEO', viewValue: 'Georgia' },
   { value: 'DEU', viewValue: 'Germany' },
   { value: 'GHA', viewValue: 'Ghana' },
   { value: 'GRC', viewValue: 'Greece' },
   { value: 'GRD', viewValue: 'Grenada' },
   { value: 'GTM', viewValue: 'Guatemala' },
   { value: 'GIN', viewValue: 'Guinea' },
   { value: 'GNB', viewValue: 'Guinea-Bissau' },
   { value: 'GUY', viewValue: 'Guyana' },
   { value: 'HTI', viewValue: 'Haiti' },
   { value: 'HND', viewValue: 'Honduras' },
   { value: 'HUN', viewValue: 'Hungary' },
   { value: 'ISL', viewValue: 'Iceland' },
   { value: 'IND', viewValue: 'India' },
   { value: 'IDN', viewValue: 'Indonesia' },
   { value: 'IRN', viewValue: 'Iran' },
   { value: 'IRQ', viewValue: 'Iraq' },
   { value: 'IRL', viewValue: 'Ireland' },
   { value: 'ISR', viewValue: 'Israel' },
   { value: 'ITA', viewValue: 'Italy' },
   { value: 'JAM', viewValue: 'Jamaica' },
   { value: 'JPN', viewValue: 'Japan' },
   { value: 'JOR', viewValue: 'Jordan' },
   { value: 'KAZ', viewValue: 'Kazakhstan' },
   { value: 'KEN', viewValue: 'Kenya' },
   { value: 'KIR', viewValue: 'Kiribati' },
   { value: 'PRK', viewValue: 'Korea (North)' },
   { value: 'KOR', viewValue: 'Korea (South)' },
   { value: 'KWT', viewValue: 'Kuwait' },
   { value: 'KGZ', viewValue: 'Kyrgyzstan' },
   { value: 'LAO', viewValue: 'Laos' },
   { value: 'LVA', viewValue: 'Latvia' },
   { value: 'LBN', viewValue: 'Lebanon' },
   { value: 'LSO', viewValue: 'Lesotho' },
   { value: 'LBR', viewValue: 'Liberia' },
   { value: 'LBY', viewValue: 'Libya' },
   { value: 'LIE', viewValue: 'Liechtenstein' },
   { value: 'LTU', viewValue: 'Lithuania' },
   { value: 'LUX', viewValue: 'Luxembourg' },
   { value: 'MDG', viewValue: 'Madagascar' },
   { value: 'MWI', viewValue: 'Malawi' },
   { value: 'MYS', viewValue: 'Malaysia' },
   { value: 'MDV', viewValue: 'Maldives' },
   { value: 'MLI', viewValue: 'Mali' },
   { value: 'MLT', viewValue: 'Malta' },
   { value: 'MHL', viewValue: 'Marshall Islands' },
   { value: 'MRT', viewValue: 'Mauritania' },
   { value: 'MUS', viewValue: 'Mauritius' },
   { value: 'MEX', viewValue: 'Mexico' },
   { value: 'FSM', viewValue: 'Micronesia' },
   { value: 'MDA', viewValue: 'Moldova' },
   { value: 'MCO', viewValue: 'Monaco' },
   { value: 'MNG', viewValue: 'Mongolia' },
   { value: 'MNE', viewValue: 'Montenegro' },
   { value: 'MAR', viewValue: 'Morocco' },
   { value: 'MOZ', viewValue: 'Mozambique' },
   { value: 'MMR', viewValue: 'Myanmar' },
   { value: 'NAM', viewValue: 'Namibia' },
   { value: 'NRU', viewValue: 'Nauru' },
   { value: 'NPL', viewValue: 'Nepal' },
   { value: 'NLD', viewValue: 'Netherlands' },
   { value: 'NZL', viewValue: 'New Zealand' },
   { value: 'NIC', viewValue: 'Nicaragua' },
   { value: 'NER', viewValue: 'Niger' },
   { value: 'NGA', viewValue: 'Nigeria' },
   { value: 'MKD', viewValue: 'North Macedonia' },
   { value: 'NOR', viewValue: 'Norway' },
   { value: 'OMN', viewValue: 'Oman' },
   { value: 'PAK', viewValue: 'Pakistan' },
   { value: 'PLW', viewValue: 'Palau' },
   { value: 'PAN', viewValue: 'Panama' },
   { value: 'PNG', viewValue: 'Papua New Guinea' },
   { value: 'PRY', viewValue: 'Paraguay' },
   { value: 'PER', viewValue: 'Peru' },
   { value: 'PHL', viewValue: 'Philippines' },
   { value: 'POL', viewValue: 'Poland' },
   { value: 'PRT', viewValue: 'Portugal' },
   { value: 'QAT', viewValue: 'Qatar' },
   { value: 'ROU', viewValue: 'Romania' },
   { value: 'RUS', viewValue: 'Russia' },
   { value: 'RWA', viewValue: 'Rwanda' },
   { value: 'KNA', viewValue: 'Saint Kitts and Nevis' },
   { value: 'LCA', viewValue: 'Saint Lucia' },
   { value: 'VCT', viewValue: 'Saint Vincent and the Grenadines' },
   { value: 'SMR', viewValue: 'San Marino' },
   { value: 'STP', viewValue: 'Sao Tome and Principe' },
   { value: 'SAU', viewValue: 'Saudi Arabia' },
   { value: 'SEN', viewValue: 'Senegal' },
   { value: 'SRB', viewValue: 'Serbia' },
   { value: 'SYC', viewValue: 'Seychelles' },
   { value: 'SLE', viewValue: 'Sierra Leone' },
   { value: 'SGP', viewValue: 'Singapore' },
   { value: 'SVK', viewValue: 'Slovakia' },
   { value: 'SVN', viewValue: 'Slovenia' },
   { value: 'SLB', viewValue: 'Solomon Islands' },
   { value: 'SOM', viewValue: 'Somalia' },
   { value: 'ZAF', viewValue: 'South Africa' },
   { value: 'SSD', viewValue: 'South Sudan' },
   { value: 'ESP', viewValue: 'Spain' },
   { value: 'LKA', viewValue: 'Sri Lanka' },
   { value: 'SDN', viewValue: 'Sudan' },
   { value: 'SUR', viewValue: 'Suriname' },
   { value: 'SWE', viewValue: 'Sweden' },
   { value: 'CHE', viewValue: 'Switzerland' },
   { value: 'SYR', viewValue: 'Syria' },
   { value: 'TWN', viewValue: 'Taiwan' },
   { value: 'TJK', viewValue: 'Tajikistan' },
   { value: 'TZA', viewValue: 'Tanzania' },
   { value: 'THA', viewValue: 'Thailand' },
   { value: 'TLS', viewValue: 'Timor-Leste' },
   { value: 'TGO', viewValue: 'Togo' },
   { value: 'TON', viewValue: 'Tonga' },
   { value: 'TTO', viewValue: 'Trinidad and Tobago' },
   { value: 'TUN', viewValue: 'Tunisia' },
   { value: 'TUR', viewValue: 'Turkey' },
   { value: 'TKM', viewValue: 'Turkmenistan' },
   { value: 'TUV', viewValue: 'Tuvalu' },
   { value: 'UGA', viewValue: 'Uganda' },
   { value: 'UKR', viewValue: 'Ukraine' },
   { value: 'ARE', viewValue: 'United Arab Emirates' },
   { value: 'GBR', viewValue: 'United Kingdom' },
   { value: 'USA', viewValue: 'United States' },
   { value: 'URY', viewValue: 'Uruguay' },
   { value: 'UZB', viewValue: 'Uzbekistan' },
   { value: 'VUT', viewValue: 'Vanuatu' },
   { value: 'VEN', viewValue: 'Venezuela' },
   { value: 'VNM', viewValue: 'Vietnam' },
   { value: 'YEM', viewValue: 'Yemen' },
   { value: 'ZMB', viewValue: 'Zambia' },
   { value: 'ZWE', viewValue: 'Zimbabwe' }
];
